// Barrel file — re-exports all types generated by ts-rs from the Rust backend.
// Regenerate the generated/ directory by running `cargo test` in the backend.

// ─── Alerts & Email ───
export type { AlertConfig } from "./generated/AlertConfig";
export type { AlertTriggers } from "./generated/AlertTriggers";
export type { DeleteSmtpConfigResponse } from "./generated/DeleteSmtpConfigResponse";
export type { SaveAlertConfigRequest } from "./generated/SaveAlertConfigRequest";
export type { SaveSmtpConfigRequest } from "./generated/SaveSmtpConfigRequest";
export type { ServerAlertConfig } from "./generated/ServerAlertConfig";
export type { SmtpConfigPublic } from "./generated/SmtpConfigPublic";
export type { TestEmailRequest } from "./generated/TestEmailRequest";
export type { TestEmailResponse } from "./generated/TestEmailResponse";
export type { UpdateServerAlertRequest } from "./generated/UpdateServerAlertRequest";

// ─── Auth & Users ───
export type { AppSettings } from "./generated/AppSettings";
export type { AuthResponse } from "./generated/AuthResponse";
export type { ChangePasswordRequest } from "./generated/ChangePasswordRequest";
export type { LoginRequest } from "./generated/LoginRequest";
export type { LogoutEverywhereResponse } from "./generated/LogoutEverywhereResponse";
export type { MeResponse } from "./generated/MeResponse";
export type { RefreshResponse } from "./generated/RefreshResponse";
export type { RegisterRequest } from "./generated/RegisterRequest";
export type { RevokeSessionRequest } from "./generated/RevokeSessionRequest";
export type { RevokeSessionResponse } from "./generated/RevokeSessionResponse";
export type { Role } from "./generated/Role";
export type { SessionInfo } from "./generated/SessionInfo";
export type { SessionListResponse } from "./generated/SessionListResponse";
export type { SetupRequest } from "./generated/SetupRequest";
export type { UpdateSettingsRequest } from "./generated/UpdateSettingsRequest";
export type { UpdateUserRoleRequest } from "./generated/UpdateUserRoleRequest";
export type { User } from "./generated/User";
export type { UserListResponse } from "./generated/UserListResponse";
export type { UserPublic } from "./generated/UserPublic";
export type { WsTicketRequest } from "./generated/WsTicketRequest";
export type { WsTicketResponse } from "./generated/WsTicketResponse";

// ─── Permissions ───
export type { EffectivePermission } from "./generated/EffectivePermission";
export type { PermissionLevel } from "./generated/PermissionLevel";
export type { RemovePermissionRequest } from "./generated/RemovePermissionRequest";
export type { ServerPermission } from "./generated/ServerPermission";
export type { ServerPermissionEntry } from "./generated/ServerPermissionEntry";
export type { ServerPermissionsResponse } from "./generated/ServerPermissionsResponse";
export type { SetPermissionRequest } from "./generated/SetPermissionRequest";

// ─── Import ───
export type { ImportFolderRequest } from "./generated/ImportFolderRequest";
export type { ImportFolderResponse } from "./generated/ImportFolderResponse";
export type { ImportUrlRequest } from "./generated/ImportUrlRequest";
export type { ImportUrlResponse } from "./generated/ImportUrlResponse";
export type { RemoteConfigEntry } from "./generated/RemoteConfigEntry";

// ─── Update Check ───
export type { UpdateCheck } from "./generated/UpdateCheck";
export type { UpdateCheckProvider } from "./generated/UpdateCheckProvider";
export type { UpdateCheckResult } from "./generated/UpdateCheckResult";
export type { UpdateCheckStatusResponse } from "./generated/UpdateCheckStatusResponse";
export type { VersionPick } from "./generated/VersionPick";

// ─── Templates ───
export type { CreateTemplateRequest } from "./generated/CreateTemplateRequest";
export type { ServerTemplate } from "./generated/ServerTemplate";
export type { TemplateListResponse } from "./generated/TemplateListResponse";
export type { UpdateTemplateRequest } from "./generated/UpdateTemplateRequest";

// ─── Dynamic Options (Tier 1: API Fetch + Mapping) ───
export type { FetchedOption } from "./generated/FetchedOption";
export type { FetchOptionsResponse } from "./generated/FetchOptionsResponse";
export type { OptionsFrom } from "./generated/OptionsFrom";
export type { OptionsSortOrder } from "./generated/OptionsSortOrder";

// ─── Pipeline / Install / Update ───
export type { ArchiveFormat } from "./generated/ArchiveFormat";
export type { ConfigParameter } from "./generated/ConfigParameter";
export type { ConfigParameterType } from "./generated/ConfigParameterType";
export type { FileOperation } from "./generated/FileOperation";
export type { PhaseKind } from "./generated/PhaseKind";
export type { PhaseLogLine } from "./generated/PhaseLogLine";
export type { PhaseProgress } from "./generated/PhaseProgress";
export type { PhaseStatus } from "./generated/PhaseStatus";
export type { PhaseStatusResponse } from "./generated/PhaseStatusResponse";
export type { PipelineStep } from "./generated/PipelineStep";
export type { ProcessConfig } from "./generated/ProcessConfig";
export type { RunPhaseRequest } from "./generated/RunPhaseRequest";
export type { RunPhaseResponse } from "./generated/RunPhaseResponse";
export type { StepAction } from "./generated/StepAction";
export type { StepCondition } from "./generated/StepCondition";
export type { StepProgress } from "./generated/StepProgress";
export type { StopSignal } from "./generated/StopSignal";

// ─── Server ───
export type { CreateServerRequest } from "./generated/CreateServerRequest";
export type { IsolationConfig } from "./generated/IsolationConfig";
export type { PaginatedServerListResponse } from "./generated/PaginatedServerListResponse";
export type { Server } from "./generated/Server";
export type { ServerConfig } from "./generated/ServerConfig";
export type { ServerListResponse } from "./generated/ServerListResponse";
export type { ServerRuntime } from "./generated/ServerRuntime";
export type { ServerStatus } from "./generated/ServerStatus";
export type { ServerWithStatus } from "./generated/ServerWithStatus";
export type { SendCommandRequest } from "./generated/SendCommandRequest";
export type { UpdateServerRequest } from "./generated/UpdateServerRequest";

// ─── Files ───
export type { ChmodRequest } from "./generated/ChmodRequest";
export type { CreateDirRequest } from "./generated/CreateDirRequest";
export type { DeleteRequest } from "./generated/DeleteRequest";
export type { FileContentResponse } from "./generated/FileContentResponse";
export type { FileEntry } from "./generated/FileEntry";
export type { FileEntryKind } from "./generated/FileEntryKind";
export type { FileListResponse } from "./generated/FileListResponse";
export type { FilePermissionsResponse } from "./generated/FilePermissionsResponse";
export type { WriteFileRequest } from "./generated/WriteFileRequest";

// ─── Per-Server Resource Stats ───
export type { ServerResourceStats } from "./generated/ServerResourceStats";

// ─── System Health ───
export type { CpuMetrics } from "./generated/CpuMetrics";
export type { DiskMetrics } from "./generated/DiskMetrics";
export type { DotnetRuntime } from "./generated/DotnetRuntime";
export type { DotnetRuntimesResponse } from "./generated/DotnetRuntimesResponse";
export type { JavaRuntime } from "./generated/JavaRuntime";
export type { JavaRuntimesResponse } from "./generated/JavaRuntimesResponse";
export type { MemoryMetrics } from "./generated/MemoryMetrics";
export type { NetworkMetrics } from "./generated/NetworkMetrics";
export type { SystemHealth } from "./generated/SystemHealth";

// ─── WebSocket ───
export type { LogLine } from "./generated/LogLine";
export type { LogStream } from "./generated/LogStream";
export type { StopPhase } from "./generated/StopPhase";
export type { StopStepInfo } from "./generated/StopStepInfo";
export type { StopProgress } from "./generated/StopProgress";
export type { WsMessage } from "./generated/WsMessage";

// ─── Typed Action Responses ───
export type { CancelPhaseResponse } from "./generated/CancelPhaseResponse";
export type { CancelStopResponse } from "./generated/CancelStopResponse";
export type { ChangePasswordResponse } from "./generated/ChangePasswordResponse";
export type { ChmodResponse } from "./generated/ChmodResponse";
export type { CreateDirResponse } from "./generated/CreateDirResponse";
export type { DeletePathResponse } from "./generated/DeletePathResponse";
export type { DeleteServerResponse } from "./generated/DeleteServerResponse";
export type { MarkInstalledResponse } from "./generated/MarkInstalledResponse";
export type { DeleteTemplateResponse } from "./generated/DeleteTemplateResponse";
export type { DeleteUserResponse } from "./generated/DeleteUserResponse";
export type { KillDirectoryProcessesResponse } from "./generated/KillDirectoryProcessesResponse";
export type { KillProcessResult } from "./generated/KillProcessResult";
export type { RemovePermissionResponse } from "./generated/RemovePermissionResponse";
export type { ResetServerResponse } from "./generated/ResetServerResponse";
export type { SendCommandResponse } from "./generated/SendCommandResponse";
export type { SendSignalResponse } from "./generated/SendSignalResponse";
export type { WriteFileResponse } from "./generated/WriteFileResponse";

// ─── SteamCMD ───
export type { SteamAppInfo } from "./generated/SteamAppInfo";
export type { SteamCmdStatus } from "./generated/SteamCmdStatus";
export type { SteamCmdStatusResponse } from "./generated/SteamCmdStatusResponse";
export type { ValidateAppResponse } from "./generated/ValidateAppResponse";

// ─── Invite Codes ───
export type { InviteCode } from "./generated/InviteCode";
export type { InviteCodePublic } from "./generated/InviteCodePublic";
export type { InvitePermissionGrant } from "./generated/InvitePermissionGrant";
export type { InviteExpiry } from "./generated/InviteExpiry";
export type { CreateInviteCodeRequest } from "./generated/CreateInviteCodeRequest";
export type { CreateInviteCodeResponse } from "./generated/CreateInviteCodeResponse";
export type { InviteCodeListResponse } from "./generated/InviteCodeListResponse";
export type { UpdateInvitePermissionsRequest } from "./generated/UpdateInvitePermissionsRequest";
export type { RedeemInviteCodeRequest } from "./generated/RedeemInviteCodeRequest";
export type { RedeemInviteCodeResponse } from "./generated/RedeemInviteCodeResponse";
export type { DeleteInviteCodeResponse } from "./generated/DeleteInviteCodeResponse";

// ─── User Permission Management ───
export type { UserPermissionSummary } from "./generated/UserPermissionSummary";
export type { UserServerPermission } from "./generated/UserServerPermission";
export type { UserPermissionListResponse } from "./generated/UserPermissionListResponse";

// ─── Sandbox Profiles ───
export type { SandboxProfile } from "./generated/SandboxProfile";
export type { SandboxCapabilities } from "./generated/SandboxCapabilities";
export type { UpdateSandboxProfileRequest } from "./generated/UpdateSandboxProfileRequest";
export type { SandboxProfileResponse } from "./generated/SandboxProfileResponse";
export type { ToggleSandboxFeatureRequest } from "./generated/ToggleSandboxFeatureRequest";
export type { ToggleSandboxFeatureResponse } from "./generated/ToggleSandboxFeatureResponse";

// ─── Errors ───
export type { ApiError } from "./generated/ApiError";
